<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy,-Scipy-and-Matplotlib" data-toc-modified-id="Numpy,-Scipy-and-Matplotlib-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy, Scipy and Matplotlib</a></span></li><li><span><a href="#NumPy" data-toc-modified-id="NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>NumPy</a></span><ul class="toc-item"><li><span><a href="#Numpy-arrays" data-toc-modified-id="Numpy-arrays-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Numpy arrays</a></span><ul class="toc-item"><li><span><a href="#Memory-layout---Python-list-vs-numpy-ndarray" data-toc-modified-id="Memory-layout---Python-list-vs-numpy-ndarray-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Memory layout - Python list vs numpy ndarray</a></span></li><li><span><a href="#Creating-arrays" data-toc-modified-id="Creating-arrays-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Creating arrays</a></span></li></ul></li><li><span><a href="#Numpy-datatypes" data-toc-modified-id="Numpy-datatypes-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Numpy datatypes</a></span></li><li><span><a href="#Working-with-numpy-arrays" data-toc-modified-id="Working-with-numpy-arrays-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Working with numpy arrays</a></span><ul class="toc-item"><li><span><a href="#numpy-ufuncs" data-toc-modified-id="numpy-ufuncs-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>numpy ufuncs</a></span></li></ul></li><li><span><a href="#Array-indexing-and-slicing" data-toc-modified-id="Array-indexing-and-slicing-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Array indexing and slicing</a></span><ul class="toc-item"><li><span><a href="#Array-filtering" data-toc-modified-id="Array-filtering-2.4.1"><span class="toc-item-num">2.4.1&nbsp;&nbsp;</span>Array filtering</a></span></li><li><span><a href="#Array-IO" data-toc-modified-id="Array-IO-2.4.2"><span class="toc-item-num">2.4.2&nbsp;&nbsp;</span>Array IO</a></span></li><li><span><a href="#Basic-statistics" data-toc-modified-id="Basic-statistics-2.4.3"><span class="toc-item-num">2.4.3&nbsp;&nbsp;</span>Basic statistics</a></span></li></ul></li><li><span><a href="#Linear-Algebra" data-toc-modified-id="Linear-Algebra-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Linear Algebra</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Solving-system-of-equations" data-toc-modified-id="Solving-system-of-equations-2.5.0.1"><span class="toc-item-num">2.5.0.1&nbsp;&nbsp;</span>Solving system of equations</a></span></li></ul></li><li><span><a href="#numpy---many-more-features" data-toc-modified-id="numpy---many-more-features-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>numpy - many more features</a></span></li></ul></li></ul></li></ul></div>

# Numpy, Scipy and Matplotlib
There are numerous scientific programs, packages and libraries written in various programming languages: 

*Mathematica, Maple, Matlab, Root, R, Numerical Recipes, etc*

For python the de-facto standard are the 
*Numpy, Scipy and Matplotlib* packages.
They allow to combine the ease and flexibility of Python programming
with efficient and powerful libraries, which provide state-of-the art functionality and fast execution also for large applications. 



# NumPy

Applications in Science and Physics often require very cpu-intensive operations, e.g:

* large equation systems
* matrices 
* numerical integration
* fourier-transformation
* random number generation
* ...

Rich legacy of numerical libraries written e.g. in 
 Fortran or C/C++ (e.g. Numerical Recipes). 
This is also used with *numpy*, which offers an interface to BLAS (Basic Linear Algebra Library) and ATLAS (Automatically Tuned Linear Algebra Software).

Moreover, *numpy* offers a very efficient array datatype `ndarray` which provides a homogeneous store for numerical data types and operations and functions for it. The backend is written in **`C`** and allows efficient vectorised or parallelized operations on large array structures.


In [1]:
import numpy as np

In [2]:
%%timeit
# std pythons lists
a = range(10000000)
b = range(10000000)
c = []
for i in range(len(a)):
  c.append(a[i] + b[i])


2.33 s ± 105 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit
# same with numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000) 
c = a + b


66.6 ms ± 1.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy arrays
The basis of numpy is the **`ndarray`**, this is a homogeneous array especially for numerical data types.
* It supports many different kinds of integer, float and boolean data types
* but homogeneous, all elements in array of same type
  * *(not quite true, elements can also be Python objects and thereby any Python type, but that's exceptional case)*
* not just a list, it contains additional information on *shape* ("n-dimensional")
* many utility functions to create, fill, store, extract, manipulate


In [5]:
# std python list very flexible
L = list(range(10)) # homogeneous list
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
# but also arbitrary elements
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [10]:
np.array(L3)

array(['True', '2', '3.0', '4'], dtype='<U32')

In [7]:
# numpy array from python list
np.array([1, 4, 2, 5, 3]) #  integer elements --> integer array

array([1, 4, 2, 5, 3])

In [8]:
# numpy array from python list
np.array([1, 4.2, 2, 5, 3]) #  one float --> float array

array([1. , 4.2, 2. , 5. , 3. ])

In [9]:
# can also enforce data type
np.array([1, 4, 2, 5, 3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

In [12]:
# will truncate
d = np.array([1, 4, 2, 5.7, 3.4, 1000000], int)

In [13]:
# datatype as specified
d.dtype

dtype('int32')

In [14]:
# float → int
d

array([      1,       4,       2,       5,       3, 1000000])

### Memory layout - Python list vs numpy ndarray
* A python list is a list of **pointers/references** to the actual objects
  * very flexible, but also inefficient when accessing large arrays
* in contrast, numpy ndarray contains directly all elements
  * efficient to process but needs to have specific data type

![Array Memory Layout](figures/array_vs_list.png)

### Creating arrays

In [15]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5, 2), dtype=float)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [17]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(2, 20, 0.1)

array([ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,
        3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,
        4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,
        5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,
        6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,
        7.5,  7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,
        8.6,  8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,
        9.7,  9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7,
       10.8, 10.9, 11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8,
       11.9, 12. , 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9,
       13. , 13.1, 13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. ,
       14.1, 14.2, 14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1,
       15.2, 15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2,
       16.3, 16.4, 16.5, 16.6, 16.7, 16.8, 16.9, 17

In [18]:
# Create an array of 11 values evenly spaced between 0 and 1
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [19]:
# Create an array of 10 values logarithmically spaced between 10**0 and 10**5
np.logspace(0, 5, 10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])

In [20]:
# can use different base
np.logspace(0, 5, 6, base = 2)

array([ 1.,  2.,  4.,  8., 16., 32.])

In [21]:
# Create an array of 5 uniformly distributed
# random values between 0 and 1
np.random.random((10,5))

array([[0.02391227, 0.09786001, 0.73654411, 0.47366092, 0.53241183],
       [0.0627105 , 0.5074695 , 0.34746208, 0.20707669, 0.72517209],
       [0.77585958, 0.74574017, 0.49129774, 0.02718034, 0.58521213],
       [0.4004125 , 0.408677  , 0.83897246, 0.805336  , 0.39828958],
       [0.63298606, 0.69573085, 0.27710191, 0.35262417, 0.13751912],
       [0.10801125, 0.78698532, 0.91215182, 0.41836952, 0.07102603],
       [0.66700514, 0.39175818, 0.5870398 , 0.53601926, 0.17037621],
       [0.53326677, 0.0250204 , 0.81169483, 0.20507208, 0.30517414],
       [0.24972531, 0.2137573 , 0.60505342, 0.4148413 , 0.49132059],
       [0.27016114, 0.98866302, 0.0028479 , 0.53031102, 0.52728891]])

In [22]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.58449485, 0.63650692, 0.37021875],
       [0.68019832, 0.23802903, 0.71762406],
       [0.74459235, 0.81330847, 0.90258111]])

In [23]:
# Create an array of 10 normal distributed
# random values with mean 0 and std deviation 1
np.random.normal(0, 1, (10,5))

array([[-0.05957696, -0.23972062, -0.6701933 ,  0.57451471, -0.59942721],
       [-0.30718094, -0.56267614, -0.03928456,  0.42826296, -1.28826183],
       [-0.39353739,  0.12537963,  1.66528206, -1.20561951, -0.14010057],
       [ 1.13983895, -0.47171395, -0.12575969,  1.63544353, -1.2325688 ],
       [-0.47662449, -0.68243176, -1.73599247, -2.22698478,  0.2209087 ],
       [ 1.70444269,  1.36182197, -0.32596845, -0.69616538,  2.01681403],
       [-0.63104006, -0.94098326,  0.30990804, -0.34976237,  1.60093925],
       [ 0.03057956,  0.18287721, -2.14948462, -0.7597552 , -0.38114709],
       [-0.99542464,  0.97706158, -0.85270153,  0.06746362,  0.91286731],
       [-1.02166224,  1.33350345,  0.7679047 , -0.86268914,  0.38967006]])

https://www-static.etp.physik.uni-muenchen.de/kurs/Computing/python/nb/nb_NumpyIntro.ipynb## Numpy datatypes
In most cases Python/numpy automatically identifies suitable data-type, though sometimes it can be useful to explicitly specify the desired type.

Here the list of supported types:


| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

In [ ]:
a=np.random.normal(0, 1, 10)
a.dtype   # data type available as field in ndarray

## Working with numpy arrays


In [24]:
a=np.array([[1,2,3,4],[4,5,6,7],[9,10,11,12]]) 
print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 12]]


In [25]:
# many fields and functions in ndarray
[m for m in dir(a) if not m.startswith('__')] # or filter(dir(a), lambda m: ...)

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

In [26]:
a.shape # layout stored in shape

(3, 4)

In [27]:
b=a.reshape(6,2) # can be changed

In [28]:
print(a.shape) # original unchanged
print(b.shape) 

(3, 4)
(6, 2)


In [29]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 9, 10],
       [11, 12]])

In [30]:
a.T # transpose

array([[ 1,  4,  9],
       [ 2,  5, 10],
       [ 3,  6, 11],
       [ 4,  7, 12]])

In [31]:
-1*a # multiply with scalar

array([[ -1,  -2,  -3,  -4],
       [ -4,  -5,  -6,  -7],
       [ -9, -10, -11, -12]])

In [32]:
a+2.1 # add scalar

array([[ 3.1,  4.1,  5.1,  6.1],
       [ 6.1,  7.1,  8.1,  9.1],
       [11.1, 12.1, 13.1, 14.1]])

In [33]:
a+a # adding arrays element-by-element

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14],
       [18, 20, 22, 24]])

In [34]:
a+b # error - requires same shape

ValueError: operands could not be broadcast together with shapes (3,4) (6,2) 

In [35]:
a*a # multiplying array element-by-element

array([[  1,   4,   9,  16],
       [ 16,  25,  36,  49],
       [ 81, 100, 121, 144]])

In [36]:
a.dot(a) # matrix multiplication -- error aligned shapes required

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [37]:
a.dot(a.reshape(4,3)) # matrix multiplication: 3x4 times 4x3 works ok

array([[ 67,  75,  88],
       [130, 147, 175],
       [235, 267, 320]])

In [38]:
a.dot(a.T)

array([[ 30,  60, 110],
       [ 60, 126, 236],
       [110, 236, 446]])

In [39]:
c=np.arange(4,8)
print(c, c.shape)

[4 5 6 7] (4,)


In [40]:
a.dot(c) # 3x4 matrix times 4-vec ok

array([ 60, 126, 236])

### numpy ufuncs
[**ufunc**](https://numpy.org/doc/stable/reference/ufuncs.html) = universal function
* operates on `ndarrays` element by element
* supports array broadcasting and type casting
* “vectorized” wrapper for a function
Commonly used mathematical functions reimplemented in `numpy` as universal functions, e.g. `math.sqrt` → `numpy.sqrt`.

In [ ]:
np.sqrt(a) # can apply std maths functions

In [ ]:
a**0.5 # and operators

In [ ]:
np.sin(a)

In [ ]:
import math
math.sin(a[0,0])

See here for detailed list of Numpy functions: 
https://scipy.github.io/old-wiki/pages/Numpy_Example_List_With_Doc.html

## Array indexing and slicing
As for Python lists there are many sophisticated ways how to access or extract elements or sub-arrays

In [ ]:
a=np.array([[1,2,3,4],[4,5,6,7],[9,10,11,12]])
a

In [ ]:
a[1,2] # 2nd line, 3rd colun (index starts at 0)

In [ ]:
a[1] # 2nd line

In [ ]:
a[-1] #  last line

In [ ]:
a[:2] # 1st and 2nd line

In [ ]:
a[:,2] # 3rd column

In [ ]:
a[:2,1:3] # ...

In [41]:
# structured array (https://numpy.org/doc/stable/user/basics.rec.html)
x = np.array([(1, 2), (3, 4)], dtype=[('a', np.int8), ('b', np.int16)])
x

array([(1, 2), (3, 4)], dtype=[('a', 'i1'), ('b', '<i2')])

In [45]:
x["a"]

array([1, 3], dtype=int8)

In [42]:
x[0], x['a'], x['b']

((1, 2), array([1, 3], dtype=int8), array([2, 4], dtype=int16))

In [43]:
x.dtype.names

('a', 'b')

### Array filtering

In [46]:
a=np.array(range(100))

In [ ]:
a

In [47]:
np.where(a%3==0)

(array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
        51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99],
       dtype=int64),)

In [51]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [48]:
a%2==0 # returns boolean array if elements fullfill criteria

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

In [49]:
a[a>80] # sub-array fullfilling criteria

array([81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
       98, 99])

In [50]:
np.where(a>80)

(array([81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99], dtype=int64),)

### Array IO

In [52]:
#data = np.loadtxt('numbers.dat') # reads numbers from text file and stores in numpy array
# also works for url
data = np.loadtxt('http://www-static.etp.physik.uni-muenchen.de/kurs/Computing/python/source/numbers.dat')

print(data)

[-1.52067e+00 -1.48203e+00  5.10425e-01  5.70107e-01  1.05585e+00
  4.47174e-01 -1.31918e+00  2.24484e-01  7.20203e-01  5.66752e-01
  7.32221e-01  6.27270e-01  1.14690e+00 -4.10935e-01  1.71971e-03
  2.89106e-01  1.16715e+00  6.00226e-02 -1.85172e+00 -1.36731e+00
  9.27019e-01 -7.23274e-01  6.31904e-01  7.93589e-01 -8.38816e-01
  2.92658e-01  2.03994e+00 -1.55009e-01 -2.52656e-01  1.66713e+00
  1.39237e+00  8.88801e-01 -1.07309e+00  4.48290e-01 -8.20842e-01
  1.22037e-02  4.42460e-01 -1.66736e+00 -3.46392e-02 -9.99998e-01
  4.81106e-02  5.65355e-01  1.25134e+00 -1.81597e-01  1.27181e+00
 -5.39457e-01 -3.36181e-01  1.47788e-01  1.51983e+00 -5.08325e-01
 -2.25669e+00 -6.95918e-01 -1.60538e+00 -1.68254e-01  1.51269e+00
  1.03994e-01 -7.97516e-01 -5.53368e-01 -1.58439e+00  2.19591e+00
 -1.07066e+00  4.12019e-01  8.13246e-01 -1.23069e+00  6.15702e-01
 -1.34514e-01 -3.85264e-02 -9.90841e-01  1.47927e+00 -3.78047e-01
  1.10984e+00  4.32740e-01 -5.19493e-01 -7.97149e-01 -3.50835e-01
 -2.45411e

In [53]:
data.mean(), data.std(), data.var(), data.min(), data.max()

(-0.0473979249, 1.0494338596029966, 1.1013114256812422, -2.4661, 2.19591)

In [58]:
a = np.array(np.arange(1,10).reshape(3,3))
print('a =',a)

a.tofile('a.data', format="%d", sep=" ") # stored as binary data (can change with sep=",", format='%d')
b = np.fromfile('a.data', dtype=int) # watch out, shape info lost
print('b =',b)

a = [[1 2 3]
 [4 5 6]
 [7 8 9]]
b = [540155953 540287027 540418101 540549175]


### Basic statistics


In [ ]:
T=np.array([1, 2, 3])
print (T.mean(), T.std(), T.var()) # Mean, std deviation, Variance

In [ ]:
T.min()

In [59]:
T=np.random.normal(10.,2.,1000) # 1000 normal distributed random numbers, mean 10, std 2
print (T.mean(), T.std(), T.var())

10.017150713599877 1.9573184250897013 3.831095417195629


In [60]:
# correlation
TP = np.array(
    [[1.3,4.5,2.8,3.9], 
     [2.7,8.7,4.7,8.2]]
)
np.corrcoef(TP)

array([[1.        , 0.98062258],
       [0.98062258, 1.        ]])

**Statistics per row, column, ...**

All the statistics functions take as first argument the 'axis', if provided one gets statistics separate for each row, column, ...

In [ ]:
a=np.arange(12).reshape(3,4)
print(a.mean()) # overall mean
print(a.mean(0)) # specify axis (0=per column)
print(a.mean(1)) # specify axis (1=per row)


## Linear Algebra

In [ ]:
a=np.arange(12).reshape(3,4)
print(a)

In [ ]:
a.diagonal() # Diagonalwerte

In [ ]:
# standard matrices
print(np.ones(3))
print(np.zeros(3))
print(np.eye(3))

#### Solving system of equations

In [ ]:
import numpy as np
from numpy.linalg import inv
a=np.array([[3,1,5],[1,0,8],[2,1,4]])
inva=inv(a) # matrix inversion
print(a)
print(inva)
np.dot(a,inva) # should give unity matrix

In [ ]:
# check with "isclose"
np.isclose(np.dot(a,inva), np.eye(3))

In [ ]:
from numpy.linalg import solve
print(a)
b=np.array([6,7,8])
x=solve(a,b) # solve equation a*x = b
print(x)
np.dot(a,x) # test: should give b


### numpy - many more features
* advanced Linalg tools 
* numerical methods, ...